version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:14.8-alpine3.18
    hostname: postgres
    environment:
      POSTGRES_DB: "todo"
      POSTGRES_USER: "todouser"
      POSTGRES_PASSWORD: "todo"
    ports:
      - "5432:5432"
    networks:
      - back-tier

  todo_app_java_backend:
    container_name: todo_app_container
    build: ./
    ports:
      - "8080:8080"
    networks:
      - back-tier

networks:
  back-tier:
    driver: bridge