CREATE DATABASE todo;
CREATE SCHEMA public;

CREATE ROLE todouser WITH
  NOSUPERUSER
  NOCREATEDB
  NOCREATEROLE
  NOINHERIT
  LOGIN
  NOREPLICATION
  NOBYPASSRLS
  CONNECTION LIMIT -1;

GRANT ALL ON SCHEMA public TO todouser;

